# docker-compose.yml
services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: irochi-tech-app
    volumes:
      - ./src:/var/www/html
    ports:
      - 5173:5173
      - 8000:80
    depends_on:
      - db
    environment:
      - PHP_MEMORY_LIMIT=512M
      - TZ=Asia/Tokyo

  db:
    image: mysql:8.0
    container_name: irochi-tech-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: irochi
      MYSQL_USER: irochi_user
      MYSQL_PASSWORD: irochi_password
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  nginx:
    image: nginx:latest
    container_name: irochi-tech-nginx
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  dbdata: